name: Build & Deploy

on:
  workflow_dispatch:

  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths:
      - "app/**.*"
      - "public/**.*"
      - "package.json"
      - "package-lock.json"
      - "next.config.json"
      - "tailwind.config.json"
      - "postcss.config.json"
      - "tsconfig.json"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "24"
  AZURE_WEBAPP_NAME: "ct-azure-openai-gpt4-chat"
  AZURE_WEBAPP_PACKAGE_PATH: "."
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
  AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
  AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
  AZURE_OPENAI_GPT4O_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_GPT4O_DEPLOYMENT }}
  AZURE_OPENAI_GPT4O_MINI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_GPT4O_MINI_DEPLOYMENT }}
  AZURE_OPENAI_GPT41_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_GPT41_DEPLOYMENT }}
  AZURE_OPENAI_GPT41_MINI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_GPT41_MINI_DEPLOYMENT }}
  AZURE_OPENAI_GPT41_NANO_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_GPT41_NANO_DEPLOYMENT }}
  AZURE_OPENAI_GPT5_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_GPT5_DEPLOYMENT }}
  AZURE_OPENAI_GPT5_MINI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_GPT5_MINI_DEPLOYMENT }}
  AZURE_OPENAI_GPT5_NANO_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_GPT5_NANO_DEPLOYMENT }}
  AZURE_OPENAI_O1_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_O1_DEPLOYMENT }}
  AZURE_OPENAI_O1_MINI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_O1_MINI_DEPLOYMENT }}
  AZURE_OPENAI_O3_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_O3_DEPLOYMENT }}
  AZURE_OPENAI_O3_MINI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_O3_MINI_DEPLOYMENT }}
  AZURE_OPENAI_O4_MINI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_O4_MINI_DEPLOYMENT }}
  MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
  APP_DISPLAY_NAME: "Cloud Team GPT Chat"

jobs:
  build-and-deploy:
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest
    steps:
      - name: üì§ Notify Teams
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ env.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: ${{ env.APP_DISPLAY_NAME }} Deployment Started
          color: info

      - name: üë∑ Checkout Repo
        uses: actions/checkout@v5

      - name: üèóÔ∏è Setup Node.js ${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true

      - name: ‚ö°  Cache node_modules and .next folder
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: ‚¨ÜÔ∏è Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: npm install --legacy-peer-deps

      - name: üõ†Ô∏è Build app
        shell: bash
        run: npm run build

      - name: üì¶ Zip all files for deployment step
        # IMPORTANT: .next is a hidden folder and will NOT be included in the zip unless we specify it
        run: zip ${{ env.AZURE_WEBAPP_NAME}}.zip ./* .next -qr

      - name: üöÄ Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME}}.zip
          type: zip

      - name: ‚ö†Ô∏è Cancelled Notification
        if: ${{ cancelled() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ env.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: ${{ env.APP_DISPLAY_NAME }} Deployment Cancelled
          color: warning

      - name: ‚õî Failure Notification
        if: ${{ failure() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ env.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: ${{ env.APP_DISPLAY_NAME }} Deployment Failed
          color: failure

      - name: üéâ Success Notification
        if: ${{ success() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ env.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: ${{ env.APP_DISPLAY_NAME }} Deployment Successful
          color: success
